# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: graker.mapmarkers::lang.plugin.marker_name

# Model Form Field configuration
form: $/graker/mapmarkers/models/marker/fields.yaml

# Model Class name
modelClass: Graker\MapMarkers\Models\Marker

# Default redirect location
defaultRedirect: graker/mapmarkers/markers

# Create page
create:
    title: graker.mapmarkers::lang.plugin.create_marker
    redirect: graker/mapmarkers/markers/update/:id
    redirectClose: graker/mapmarkers/markers

# Update page
update:
    title: graker.mapmarkers::lang.plugin.edit_marker
    redirect: graker/mapmarkers/markers
    redirectClose: graker/mapmarkers/markers

# Preview page
preview:
    title: graker.mapmarkers::lang.plugin.preview_marker
