# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Marker

# Model Form Field configuration
form: $/graker/mapmarkers/models/marker/fields.yaml

# Model Class name
modelClass: Graker\MapMarkers\Models\Marker

# Default redirect location
defaultRedirect: graker/mapmarkers/markers

# Create page
create:
    title: Create Marker
    redirect: graker/mapmarkers/markers/update/:id
    redirectClose: graker/mapmarkers/markers

# Update page
update:
    title: Edit Marker
    redirect: graker/mapmarkers/markers
    redirectClose: graker/mapmarkers/markers

# Preview page
preview:
    title: Preview Marker